
-- hsqldb start init

drop table simple_user if exists;


create table simple_user (
	id int generated by default as identity(start with 1000) not null,
	name varchar(255) not null,
	email varchar(255) not null,
	constraint pk_simple_user primary key (id)
);

-- hsqldb init finished .

