
-- derby init start

drop table simple_user;

create table simple_user (
	id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

-- derby init finished .
